image:
  repository: placeholder
  tag: "placeholder"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

replicaCount: 2

autoscaling:
  enabled: false
  
serviceAccount:
create: false
name: ""