image:
  repository: 793264560878.dkr.ecr.us-east-1.amazonaws.com/register-app
  tag: "1.0.0-6"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

replicaCount: 2

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

httpRoute:
  enabled: false